language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-slack.gemspec
- gem install sensu-plugins-slack-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: EqJH4o+MAFbzkZQB76PESuK54p2M8iyHe7aQ1iPhKdCm2oPTpU6j2ymbGl38ccmHt6vXpmVzF6CIi4V7EHNK+n+Id+5oAcJpZTt/HxratlKM48le3ycYBt7cPlZjslFNRe/Zp+dsFYqwqk4WYSCJhIekaDfQcM1Snee7Auhc1UI=
  gem: sensu-plugins-slack
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-slack
